package:
  name: meld-dev-test
  version: {{ environ['VERSTRING'] }}


source:
  path: /io # [linux]
  path: /Users/travis/build/maccallumlab/meld #[osx]

requirements:
  build:
    - cmake
    - doxygen #[not osx]
    - swig
    - eigen3
    - python
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - openmm
    - sphinx
    - mock
    - six
    - sphinx_rtd_theme ==0.1.9
    - mpi4py

  run:
    - ambermini
    - python
    - openmm
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - mock
    - six
    - mpi4py
    - scikit-learn >=0.18.0

test:
  imports:
    - meld
    - meldplugin
  commands:
    - python -m unittest discover meld.test

about:
    home: https://meldmd.org
